name: Deployer
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Build examples
        run: yarn examples:build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./examples/build
